name: deliver-ios

on:
  pull_request:
    types:
      - opened

jobs:
  run_if:
    if: startsWith(github.head_ref, 'releases/')
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "The head of this PR starts with 'releases/'"
      - name: step2
        run: echo end
