name: job deliver

on:
  workflow_call:
    secrets:
      algolia_application_id:
        required: true
      algolia_api_key:
        required: true
      certificate_p12:
        required: true
      certificate_password:
        required: true
      provisioning_profile:
        required: true
      apple_id:
        required: true
      apple_app_pass:
        required: true

jobs:
  deliver:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create .env
        shell: bash
        run: |
          touch .env
          echo "APPLICATION_ID=${{ secrets.algolia_application_id }}" >> .env
          echo "API_KEY=${{ secrets.algolia_api_key }}" >> .env

      - name: Import Provisioning Profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo -n ${{ secrets.provisioning_profile }} | base64 -d > ~/Library/MobileDevice/Provisioning\ Profiles/distribution.mobileprovision

      - name: Import Distribution Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.certificate_p12 }}
          p12-password: ${{ secrets.certificate_password }}

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Run flutter version
        run: flutter --version

      - name: Run flutter pub get
        run: flutter pub get

      - name: Build ipa
        run: flutter build ipa --export-options-plist=./ios/ExportOptions.plist

      - name: Upload to App Store Connect
        run: xcrun altool --upload-app --type ios -f "build/ios/ipa/algolia_search_client.ipa" -u "${{ secrets.apple_id }}" -p "${{ secrets.apple_app_pass }}"
