name: workflow pull request review approve

on:
  pull_request_review:
    types: [submitted]

jobs:
  approved-check:
    if: |
      github.event.review.state == 'approved' &&
      contains(github.event.pull_request.labels.*.name, 'approved') == false
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - run: |
          echo "This PR was approved1"
          echo "This PR was approved2"
          echo ${{ github.event.review.state }}
          exit 0

  next-job:
    needs: [approved-check]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: next job
        run: echo run next job
# on:
#   pull_request_review:
#     types: [submitted]
#   workflow_dispatch:

# jobs:
#   approve-check:
#     runs-on: ubuntu-latest
#     timeout-minutes: 30
#     if: |
#       startsWith(github.head_ref, 'releases/') &&
#       github.event.review.state == 'approved' &&
#       contains(github.event.pull_request.labels.*.name, 'approved') == false
#     steps:
#       - name: Label when approved
#         uses: pullreminders/label-when-approved-action@master
#         env:
#           APPROVALS: "1"
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           ADD_LABEL: "approved"
#       - name: Add approved
#         run: echo Add approved

# next-job:
#   needs: [approve-check]
#   runs-on: ubuntu-latest
#   timeout-minutes: 30
#   steps:
#     - name: next job
#       run: echo run next job
