name: workflow release

on:
  pull_request:
    types:
      - opened
  workflow_dispatch:

jobs:
  analyze-job:
    if: startsWith(github.head_ref, 'releases/')
    uses: ./.github/workflows/analyze.job.yaml
  test-job:
    if: startsWith(github.head_ref, 'releases/')
    uses: ./.github/workflows/test.job.yaml
  deliver-job:
    needs: [analyze-job, test-job]
    if: startsWith(github.head_ref, 'releases/')
    uses: ./.github/workflows/deliver.job.yaml
    secrets:
      secrets: inherit
